image: registry.choerodon.com.cn/tools/cifront:0.5.0

stages:
  - docker_build

docker_build:
  image: registry.choerodon.com.cn/tools/cibase:0.5.0
  stage: docker_build
  script:
    - docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} .
    - docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
    - chart_build
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^feature-.*$/
    - tags

.auto_devops: &auto_devops |
    curl -o .auto_devops.sh \
        "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"
    source .auto_devops.sh

before_script:
  - *auto_devops
