image: registry.choerodon.com.cn/tools/cifront:0.5.0

stages:
  - broken_link_check
  - docker_build

broken_link_check:
  image: registry.choerodon.com.cn/tools/cifront:0.5.0
  stage: broken_link_check
  script:
    - npm install broken-link-checker -g
    - blc http://website.staging.saas.hand-china.com/zh/ -ro --exclude "http://website.staging.saas.hand-china.com/en/" --exclude "http://localhost:8080/manager/swagger-ui.html" --exclude "https://www.virtualbox.org/wiki/Download_Old_Builds_5_1" --exclude "https:/www.python.org/downloads/release/python-2712/" --exclude "https:/www.python.org/downloads/release/python-2712/" --exclude "http://www.liquibase.org/"
  only:
    - /^hotfix-check.*$/
docker_build:
  image: registry.choerodon.com.cn/tools/cibase:0.5.0
  stage: docker_build
  script:
    - docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} .
    - docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
    - chart_build
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - tags

.auto_devops: &auto_devops |
    curl -o .auto_devops.sh \
        "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"
    source .auto_devops.sh

before_script:
  - *auto_devops
